// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SearchTool_ServerSide.Data;

#nullable disable

namespace SearchTool_ServerSide.Migrations
{
    [DbContext(typeof(SearchToolDBContext))]
    [Migration("20250708221323_ClassTypeMainCompany")]
    partial class ClassTypeMainCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SearchTool_ServerSide.Dtos.SearchLogDtos.SearchLogReadDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BinId")
                        .HasColumnType("integer");

                    b.Property<string>("BinName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NDC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("PcnId")
                        .HasColumnType("integer");

                    b.Property<string>("PcnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RxgroupId")
                        .HasColumnType("integer");

                    b.Property<string>("RxgroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.ToTable("SearchLogReadDto");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MainCompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MainCompanyId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1",
                            Location = "Thousand Oaks",
                            MainCompanyId = 1,
                            Name = "California Dermatology Institute Thousand Oaks"
                        },
                        new
                        {
                            Id = 2,
                            Code = "2",
                            Location = "Northridge",
                            MainCompanyId = 1,
                            Name = "California Dermatology Institute Northridge"
                        },
                        new
                        {
                            Id = 3,
                            Code = "3",
                            Location = "Huntington Park",
                            MainCompanyId = 1,
                            Name = "California Dermatology Institute Huntington Park"
                        },
                        new
                        {
                            Id = 4,
                            Code = "4",
                            Location = "Palmdale",
                            MainCompanyId = 1,
                            Name = "California Dermatology Institute Palmdale"
                        },
                        new
                        {
                            Id = 5,
                            Code = "5",
                            Location = "VIRTUAL",
                            MainCompanyId = 1,
                            Name = "VIRTUAL"
                        },
                        new
                        {
                            Id = 6,
                            Code = "6",
                            Location = "VIRTUAL",
                            MainCompanyId = 2,
                            Name = "ASP"
                        });
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassTypeId");

                    b.ToTable("ClassInfos");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInsurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassInfoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BestNet")
                        .HasColumnType("numeric");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("InsuranceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScriptCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScriptDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InsuranceId", "ClassInfoId", "Date", "BranchId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ClassInfoId");

                    b.HasIndex("DrugId");

                    b.ToTable("ClassInsurances");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInsuranceV2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BestNet")
                        .HasColumnType("numeric");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DrugClassV2Id")
                        .HasColumnType("integer");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<string>("InsuranceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScriptCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScriptDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugClassV2Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("ClassInsuranceV2s");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInsuranceV3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BestNet")
                        .HasColumnType("numeric");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DrugClassV3Id")
                        .HasColumnType("integer");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<string>("InsuranceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScriptCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScriptDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugClassV3Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("ClassInsuranceV3s");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInsuranceV4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BestNet")
                        .HasColumnType("numeric");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DrugClassV4Id")
                        .HasColumnType("integer");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<string>("InsuranceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScriptCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScriptDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugClassV4Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("ClassInsuranceV4s");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClassTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Just for Testing",
                            Name = "TestClass"
                        });
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ACQ")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AWP")
                        .HasColumnType("numeric");

                    b.Property<string>("ApplicationNumber")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("text");

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.Property<string>("Ingrdient")
                        .HasColumnType("text");

                    b.Property<string>("NDC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<decimal?>("Rxcui")
                        .HasColumnType("numeric");

                    b.Property<string>("Strength")
                        .HasColumnType("text");

                    b.Property<string>("StrengthUnit")
                        .HasColumnType("text");

                    b.Property<string>("TECode")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugBranch", b =>
                {
                    b.Property<string>("DrugNDC")
                        .HasColumnType("text");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("DrugNDC", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("DrugBranches");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugClass", b =>
                {
                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("DrugId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("DrugClasses");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugClassV2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrugClassV2s");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugClassV3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrugClassV3s");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugClassV4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrugClassV4s");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugEPCMOA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<int>("EPCMOAClassId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("EPCMOAClassId");

                    b.ToTable("DrugEPCMOAs");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugInsurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AcquisitionCost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("InsurancePayment")
                        .HasColumnType("numeric");

                    b.Property<string>("NDCCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Net")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PatientPayment")
                        .HasColumnType("numeric");

                    b.Property<string>("Prescriber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("ScriptCode")
                        .HasColumnType("text");

                    b.HasKey("InsuranceId", "DrugId", "BranchId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugId");

                    b.ToTable("DrugInsurances");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugMedi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CCSPanelAuthority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CostCeilingTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<string>("DrugNDC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtendedDuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NonCapitatedDrugIndicator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriorAuthorization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.ToTable("DrugMedis");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.EPCMOAClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EPCMOAClasses");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HelpDeskNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.InsurancePCN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<string>("PCN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.ToTable("InsurancePCNs");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.InsuranceRx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InsurancePCNId")
                        .HasColumnType("integer");

                    b.Property<string>("RxGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePCNId");

                    b.ToTable("InsuranceRxes");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.MainCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassTypeId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("MainCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassTypeId = 1,
                            Name = "California Dermatology",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassTypeId = 1,
                            Name = "Spark Medi-Cal",
                            SpecialtyId = 1
                        });
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddtionalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("TotalAcquisitionCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInsurancePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPatientPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcquisitionCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AddtionalCost")
                        .HasColumnType("numeric");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("DrugNDC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InsurancePay")
                        .HasColumnType("numeric");

                    b.Property<int?>("InsuranceRxId")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PatientPay")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DrugNDC");

                    b.HasIndex("InsuranceRxId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ScriptItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcquisitionCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("InsurancePayment")
                        .HasColumnType("numeric");

                    b.Property<string>("NDCCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PatientPayment")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("RemainingStock")
                        .HasColumnType("integer");

                    b.Property<string>("RxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScriptId")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("InsuranceId");

                    b.HasIndex("ScriptId");

                    b.HasIndex("UserEmail");

                    b.ToTable("ScriptItems");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.SearchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BinId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DrugNDC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("PcnId")
                        .HasColumnType("integer");

                    b.Property<int?>("RxgroupId")
                        .HasColumnType("integer");

                    b.Property<string>("SearchType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("BinId");

                    b.HasIndex("DrugNDC");

                    b.HasIndex("PcnId");

                    b.HasIndex("RxgroupId");

                    b.HasIndex("UserEmail");

                    b.ToTable("SearchLogs");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dermatology specialty"
                        });
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ServerSide.Models.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScriptCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Dtos.SearchLogDtos.SearchLogReadDto", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.OrderItem", null)
                        .WithOne("SearchLogReadDto")
                        .HasForeignKey("SearchTool_ServerSide.Dtos.SearchLogDtos.SearchLogReadDto", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Branch", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.MainCompany", "MainCompany")
                        .WithMany("Branches")
                        .HasForeignKey("MainCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCompany");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInfo", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.ClassType", "ClassType")
                        .WithMany("ClassInfos")
                        .HasForeignKey("ClassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassType");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInsurance", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.ClassInfo", "ClassInfo")
                        .WithMany()
                        .HasForeignKey("ClassInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.InsuranceRx", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ClassInfo");

                    b.Navigation("Drug");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInsuranceV2", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.DrugClassV2", "DrugClassV2")
                        .WithMany()
                        .HasForeignKey("DrugClassV2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.InsuranceRx", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");

                    b.Navigation("DrugClassV2");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInsuranceV3", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.DrugClassV3", "DrugClassV3")
                        .WithMany()
                        .HasForeignKey("DrugClassV3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.InsuranceRx", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");

                    b.Navigation("DrugClassV3");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInsuranceV4", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.DrugClassV4", "DrugClassV4")
                        .WithMany()
                        .HasForeignKey("DrugClassV4Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.InsuranceRx", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");

                    b.Navigation("DrugClassV4");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugBranch", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugNDC")
                        .HasPrincipalKey("NDC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugClass", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.ClassInfo", "ClassInfo")
                        .WithMany("DrugClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany("DrugClasses")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassInfo");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugEPCMOA", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.EPCMOAClass", "EPCMOAClass")
                        .WithMany("DrugEPCMOAs")
                        .HasForeignKey("EPCMOAClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("EPCMOAClass");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugInsurance", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.InsuranceRx", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugMedi", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.InsurancePCN", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Insurance", "Insurance")
                        .WithMany("InsurancePCNs")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.InsuranceRx", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.InsurancePCN", "InsurancePCN")
                        .WithMany("InsuranceRxs")
                        .HasForeignKey("InsurancePCNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePCN");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Log", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserEmail")
                        .HasPrincipalKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.MainCompany", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.ClassType", "ClassType")
                        .WithMany("MainCompanies")
                        .HasForeignKey("ClassTypeId");

                    b.HasOne("SearchTool_ServerSide.Models.Specialty", "Specialty")
                        .WithMany("MainCompanies")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassType");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.OrderItem", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugNDC")
                        .HasPrincipalKey("NDC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.InsuranceRx", "InsuranceRx")
                        .WithMany()
                        .HasForeignKey("InsuranceRxId");

                    b.HasOne("SearchTool_ServerSide.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("InsuranceRx");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ScriptItem", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.InsuranceRx", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerSide.Models.Script", "Script")
                        .WithMany("ScriptItems")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.User", "Prescriber")
                        .WithMany()
                        .HasForeignKey("UserEmail")
                        .HasPrincipalKey("Email")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Insurance");

                    b.Navigation("Prescriber");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.SearchLog", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.InsuranceRx", "InsuranceRx")
                        .WithMany()
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugNDC")
                        .HasPrincipalKey("NDC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.InsurancePCN", "InsurancePCN")
                        .WithMany()
                        .HasForeignKey("PcnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SearchTool_ServerSide.Models.Insurance", "Insurance")
                        .WithMany()
                        .HasForeignKey("RxgroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SearchTool_ServerSide.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserEmail")
                        .HasPrincipalKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Insurance");

                    b.Navigation("InsurancePCN");

                    b.Navigation("InsuranceRx");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.User", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("ServerSide.Models.Script", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Branch", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassInfo", b =>
                {
                    b.Navigation("DrugClasses");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.ClassType", b =>
                {
                    b.Navigation("ClassInfos");

                    b.Navigation("MainCompanies");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Drug", b =>
                {
                    b.Navigation("DrugClasses");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.EPCMOAClass", b =>
                {
                    b.Navigation("DrugEPCMOAs");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Insurance", b =>
                {
                    b.Navigation("InsurancePCNs");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.InsurancePCN", b =>
                {
                    b.Navigation("InsuranceRxs");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.MainCompany", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.OrderItem", b =>
                {
                    b.Navigation("SearchLogReadDto")
                        .IsRequired();
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Specialty", b =>
                {
                    b.Navigation("MainCompanies");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.User", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("ServerSide.Models.Script", b =>
                {
                    b.Navigation("ScriptItems");
                });
#pragma warning restore 612, 618
        }
    }
}
