using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SearchTool_ServerSide.Migrations
{
    /// <inheritdoc />
    public partial class scripttable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Safe drop if table does not exist
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""DrugDiseases"" CASCADE;");

            // Safe add columns to ScriptItems
            migrationBuilder.Sql(@"ALTER TABLE ""ScriptItems"" ADD COLUMN IF NOT EXISTS ""OriginalNetProfit"" numeric;");
            migrationBuilder.Sql(@"ALTER TABLE ""ScriptItems"" ADD COLUMN IF NOT EXISTS ""Priority"" text;");
            migrationBuilder.Sql(@"ALTER TABLE ""ScriptItems"" ADD COLUMN IF NOT EXISTS ""RxStatus"" text;");
            migrationBuilder.Sql(@"ALTER TABLE ""ScriptItems"" ADD COLUMN IF NOT EXISTS ""Status"" text;");

            // Safe add columns to Logs
            migrationBuilder.Sql(@"ALTER TABLE ""Logs"" ADD COLUMN IF NOT EXISTS ""Description"" text;");
            migrationBuilder.Sql(@"ALTER TABLE ""Logs"" ADD COLUMN IF NOT EXISTS ""DeviceInfo"" text;");
            migrationBuilder.Sql(@"ALTER TABLE ""Logs"" ADD COLUMN IF NOT EXISTS ""IpAddress"" text;");

            // Safe create Chats table
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""Chats"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" integer NOT NULL,
    ""Show"" boolean NOT NULL,
    ""TempChat"" boolean NOT NULL,
    CONSTRAINT ""PK_Chats"" PRIMARY KEY (""Id"")
);
");

            // Safe create Wholesalers table
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""Wholesalers"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Name"" text NOT NULL,
    ""IsActive"" boolean NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone NULL,
    CONSTRAINT ""PK_Wholesalers"" PRIMARY KEY (""Id"")
);
");

            // Safe create Messages table
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""Messages"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Role"" character varying(10) NOT NULL,
    ""Text"" text NOT NULL,
    ""Timestamp"" timestamp with time zone NOT NULL,
    ""Show"" boolean NOT NULL,
    ""ChatId"" integer NOT NULL,
    CONSTRAINT ""PK_Messages"" PRIMARY KEY (""Id"")
);
");

            // Safe create Messages -> Chats foreign key
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_Messages_Chats_ChatId'
    ) THEN
        ALTER TABLE ""Messages""
        ADD CONSTRAINT ""FK_Messages_Chats_ChatId""
        FOREIGN KEY (""ChatId"")
        REFERENCES ""Chats"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            // Safe create DrugWholesaler table
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""DrugWholesaler"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""DrugId"" integer NOT NULL,
    ""WholesalerId"" integer NOT NULL,
    ""Price"" numeric NOT NULL,
    ""PriceDate"" timestamp with time zone NOT NULL,
    ""QuarterYear"" text NULL,
    ""SourceFileName"" text NULL,
    ""IsActive"" boolean NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone NULL,
    CONSTRAINT ""PK_DrugWholesaler"" PRIMARY KEY (""Id"")
);
");

            // Safe create DrugWholesaler -> Drugs foreign key
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_DrugWholesaler_Drugs_DrugId'
    ) THEN
        ALTER TABLE ""DrugWholesaler""
        ADD CONSTRAINT ""FK_DrugWholesaler_Drugs_DrugId""
        FOREIGN KEY (""DrugId"")
        REFERENCES ""Drugs"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            // Safe create DrugWholesaler -> Wholesalers foreign key
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_DrugWholesaler_Wholesalers_WholesalerId'
    ) THEN
        ALTER TABLE ""DrugWholesaler""
        ADD CONSTRAINT ""FK_DrugWholesaler_Wholesalers_WholesalerId""
        FOREIGN KEY (""WholesalerId"")
        REFERENCES ""Wholesalers"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            // Safe create DrugWholesalerPrescribers table
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""DrugWholesalerPrescribers"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""DrugId"" integer NOT NULL,
    ""WholesalerId"" integer NOT NULL,
    ""PrescriberId"" integer NOT NULL,
    ""Price"" numeric NOT NULL,
    ""AWP"" numeric NULL,
    ""WAC"" numeric NULL,
    ""ASP"" numeric NULL,
    ""MAC"" numeric NULL,
    ""BillingUnit"" text NULL,
    ""DrugClass"" text NULL,
    ""PriceDate"" timestamp with time zone NOT NULL,
    ""QuarterYear"" text NULL,
    ""SourceFileName"" text NULL,
    ""SourcePath"" text NULL,
    ""IsActive"" boolean NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_DrugWholesalerPrescribers"" PRIMARY KEY (""Id"")
);
");

            // Safe create DrugWholesalerPrescribers -> Drugs foreign key
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_DrugWholesalerPrescribers_Drugs_DrugId'
    ) THEN
        ALTER TABLE ""DrugWholesalerPrescribers""
        ADD CONSTRAINT ""FK_DrugWholesalerPrescribers_Drugs_DrugId""
        FOREIGN KEY (""DrugId"")
        REFERENCES ""Drugs"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            // Safe create DrugWholesalerPrescribers -> Users foreign key
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_DrugWholesalerPrescribers_Users_PrescriberId'
    ) THEN
        ALTER TABLE ""DrugWholesalerPrescribers""
        ADD CONSTRAINT ""FK_DrugWholesalerPrescribers_Users_PrescriberId""
        FOREIGN KEY (""PrescriberId"")
        REFERENCES ""Users"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            // Safe create DrugWholesalerPrescribers -> Wholesalers foreign key
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_DrugWholesalerPrescribers_Wholesalers_WholesalerId'
    ) THEN
        ALTER TABLE ""DrugWholesalerPrescribers""
        ADD CONSTRAINT ""FK_DrugWholesalerPrescribers_Wholesalers_WholesalerId""
        FOREIGN KEY (""WholesalerId"")
        REFERENCES ""Wholesalers"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            // Safe update seed data only if row/table exists
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'DiseaseVisibilitySettings'
    ) THEN
        UPDATE ""DiseaseVisibilitySettings""
        SET ""UpdatedAt"" = TIMESTAMPTZ '2026-05-11 19:26:02.0995746+00'
        WHERE ""Id"" = 1;
    END IF;
END $$;
");

            // Safe indexes
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DrugWholesaler_DrugId"" ON ""DrugWholesaler"" (""DrugId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DrugWholesaler_WholesalerId"" ON ""DrugWholesaler"" (""WholesalerId"");");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DrugWholesalerPrescribers_DrugId"" ON ""DrugWholesalerPrescribers"" (""DrugId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DrugWholesalerPrescribers_PrescriberId"" ON ""DrugWholesalerPrescribers"" (""PrescriberId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DrugWholesalerPrescribers_WholesalerId"" ON ""DrugWholesalerPrescribers"" (""WholesalerId"");");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Messages_ChatId_Timestamp"" ON ""Messages"" (""ChatId"", ""Timestamp"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""DrugWholesaler"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""DrugWholesalerPrescribers"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Messages"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Wholesalers"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Chats"" CASCADE;");

            migrationBuilder.Sql(@"ALTER TABLE ""ScriptItems"" DROP COLUMN IF EXISTS ""OriginalNetProfit"";");
            migrationBuilder.Sql(@"ALTER TABLE ""ScriptItems"" DROP COLUMN IF EXISTS ""Priority"";");
            migrationBuilder.Sql(@"ALTER TABLE ""ScriptItems"" DROP COLUMN IF EXISTS ""RxStatus"";");
            migrationBuilder.Sql(@"ALTER TABLE ""ScriptItems"" DROP COLUMN IF EXISTS ""Status"";");

            migrationBuilder.Sql(@"ALTER TABLE ""Logs"" DROP COLUMN IF EXISTS ""Description"";");
            migrationBuilder.Sql(@"ALTER TABLE ""Logs"" DROP COLUMN IF EXISTS ""DeviceInfo"";");
            migrationBuilder.Sql(@"ALTER TABLE ""Logs"" DROP COLUMN IF EXISTS ""IpAddress"";");

            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""DrugDiseases"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""DiseaseId"" integer NOT NULL,
    ""DrugId"" integer NOT NULL,
    ""UserId"" integer NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""Show"" boolean NOT NULL,
    ""userEmail"" text NOT NULL,
    CONSTRAINT ""PK_DrugDiseases"" PRIMARY KEY (""Id"")
);
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_DrugDiseases_Diseases_DiseaseId'
    ) THEN
        ALTER TABLE ""DrugDiseases""
        ADD CONSTRAINT ""FK_DrugDiseases_Diseases_DiseaseId""
        FOREIGN KEY (""DiseaseId"")
        REFERENCES ""Diseases"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_DrugDiseases_Drugs_DrugId'
    ) THEN
        ALTER TABLE ""DrugDiseases""
        ADD CONSTRAINT ""FK_DrugDiseases_Drugs_DrugId""
        FOREIGN KEY (""DrugId"")
        REFERENCES ""Drugs"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_DrugDiseases_Users_UserId'
    ) THEN
        ALTER TABLE ""DrugDiseases""
        ADD CONSTRAINT ""FK_DrugDiseases_Users_UserId""
        FOREIGN KEY (""UserId"")
        REFERENCES ""Users"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'DiseaseVisibilitySettings'
    ) THEN
        UPDATE ""DiseaseVisibilitySettings""
        SET ""UpdatedAt"" = TIMESTAMPTZ '2026-03-12 19:33:18.2349627+00'
        WHERE ""Id"" = 1;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DrugDiseases_DiseaseId"" ON ""DrugDiseases"" (""DiseaseId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DrugDiseases_DrugId"" ON ""DrugDiseases"" (""DrugId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DrugDiseases_UserId"" ON ""DrugDiseases"" (""UserId"");");
        }
    }
}